baseURL = 'https://richters.netlify.app/'
languageCode = 'en-us'
title = 'Richters Ølstue'
paginate = 3
summaryLength = 40

[[menu.main]]
name = "Kontakt Os | Richters"
url = "/contact"
weight = 2

[[menu.main]]
name = "Events | Richters"
url = "/events"
weight = 2

[params]
dateFormat = "2. Jan, 2006"
