baseURL = 'https://richtersoelstue.dk/'
languageCode = 'en-us'
title = 'Richters Ølstue'
paginate = 3
summaryLength = 40

[[menu.main]]
name = "Kontakt Os | Richters Ølstue"
url = "/kontakt"
weight = 2

[[menu.main]]
name = "Events | Richters Ølstue"
url = "/events"
weight = 2

[[menu.main]]
name = "Menukort | Richters Ølstue"
url = "/menu"
weight = 2

[params]
dateFormat = "2. Jan, 2006"
